---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerynx-ingress
  namespace: seerynx
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: seerynx.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: seerynx-frontend
                port:
                  number: 80