apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: seerynx
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: seerynx
      owner: seerynx
      secret:
        name: postgres-credentials
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"